### ISSUE TITLE
[Suggestion] Make Evolution start adding items when enabled

### ISSUE THREAD

**Issue by Jarthuzad** [Moffein/AutoArtifact#1]
I'm unsure if this is outside the scope of this mod, but as is, Evolution adds all previous stages' worth of items once it is enabled, and it would be cool if it only started to add items once its enable, as I would like to use it for very late game and not create a sudden spike.

**Comment by Moffein** [comment]
Unfortunately, that would be outside the scope of this mod since it would require rewriting the Vanilla code for Evolution.
